### ISSUE TITLE
[BUG] SemanticChunker raises UnboundLocalError: local variable 'threshold' referenced before assignment 

### ISSUE THREAD

**Issue by arpesenti** [chonkie-ai/chonkie#88]
When using the SemanticChunker with threshold='auto' and a piece of text containing only two identical (or very similar) sentences the following error is raised:

```
Traceback (most recent call last):
  File "/usr/lib/python3.10/concurrent/futures/process.py", line 246, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "model_store.py", line 186, in _chunk
    chunks = semantic_chunker.chunk(text)
  File "/virtualenv/lib/python3.10/site-packages/chonkie/chunker/semantic.py", line 513, in chunk
    self.similarity_threshold = self._calculate_similarity_threshold(sentences)
  File "/virtualenv/lib/python3.10/site-packages/chonkie/chunker/semantic.py", line 365, in _calculate_similarity_threshold
    return self._calculate_threshold_via_binary_search(sentences)
  File "/virtualenv/lib/python3.10/site-packages/chonkie/chunker/semantic.py", line 349, in _calculate_threshold_via_binary_search
    return threshold
UnboundLocalError: local variable 'threshold' referenced before assignment
```

`threshold` is not defined because the while loop condition `abs(high - low) > self.threshold_step` is never met for the default `threshold_step` 0.01 or any small step if the sentences are identical.

**Comment by arpesenti** [comment]
I have opened the pull request #89 to initialise threshold before the loop.

**Comment by arpesenti** [comment]
Actually the issue is reproducible also with any piece of text containing only two sentences: `low` and `high` are always equal in that case

**Comment by bhavnicksm** [comment]
Hey @arpesenti!

😱 WOAH! That's such a good catch~! Thanks for the PR... will have a look right away!

Thanks! 😊
